# NumPy package

## Objective

* learn about n-dimensional arrays
* understand properties of arrays
* learn how to apply functions to n-dimensional arrays

## Installing NumPy

Open a terminal and install NumPy with the following command
```
python -m pip install numpy
```

## Importing NumPy

* we import `NumPy` under `np` alias
```
import numpy as np
```

In [10]:
import numpy as np

## NumPy Arrays

* the array in NumPy is called **ndarray** (n-dimensional array)
* the array is a table (list) of elements. It's created from Python list.
* the elements are all of the **same type** and indexed by a tuple of non-negative integers
* the dimensions are called _axes_


## Creating Array

* we use the `array()` function to create an array

* example of definition of a point in a 3D space

In [11]:
pointA = np.array([0, 1, 2]) # 3D point called pointA
print('pointA:', pointA)

pointA [0 1 2]


* example of vector in 3D

In [18]:
pointB = np.array([3, 4, 5]) # 3D point called pointB
print('pointB:', pointB)

vectAB = np.array([pointA, pointB]) # vector AB
print('vectAB:', vectAB)

vectAB2 = np.array([[0, 1, 2], 
                    [3, 4, 5]]) # another definition of vector
print('vectAB2:', vectAB2)

pointB: [3 4 5]
vectAB: [[0 1 2]
 [3 4 5]]
vectAB2: [[0 1 2]
 [3 4 5]]


* example of matrix 3x3

In [20]:
matM = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])
print('matM:', matM);

matM: [[0 1 2]
 [3 4 5]
 [6 7 8]]


* NumPy Array is of type `ndarray`

In [22]:
type(matM)

numpy.ndarray

## NumPy Array functions

* we use `ndarray.ndim` to get the number of axes of the array

In [25]:
print('dim of pointA:', pointA.ndim)
print('dim of pointB:', pointB.ndim)
print('dim of matM:', matM.ndim)

dim of pointA: 1
dim of pointB: 1
dim of matM: 2


* we use `ndarray.shape` to get the dimensions of the array. It's a tuple of integers indicating the size of the array in each dimension

In [27]:
print('shape of pointB:', pointB.shape)
print('shape of matM:', matM.shape)

shape of pointB: (3,)
shape of matM: (3, 3)


In [37]:
matN = np.array([pointA, [0, 0, 0], pointB, pointB, pointA])
print(matN)
print('shape of matN:', matN.shape)

[[0 1 2]
 [0 0 0]
 [3 4 5]
 [3 4 5]
 [0 1 2]]
shape of matN: (5, 3)


* we use `ndarray.size` to get the total number of elements of the array. It's the product of the elements of `shape`.

In [48]:
print('nb. of elements of matN:', matN.size)

nb. of elements of matN: 15


15

* we use `ndarray.dtype` to get the type of elements stored in the array.
* you can specify the dtype on array creation

In [41]:
print('type of elements in matN:', matN.dtype)

type of elements in matN: int64


In [50]:
g = np.array([[1], [2], [3]], dtype=np.int32)
print(g)
g.dtype

[[1]
 [2]
 [3]]


dtype('int32')

In [49]:
h = np.array([[1], [2], [3]], dtype=np.float64)
print(h)
h.dtype

[[1.]
 [2.]
 [3.]]


dtype('float64')

* we use `ndarray.reshape` to reshape the array

In [57]:
matN2 = matN.reshape(3, 5)

print('matN:', matN, 'shape:', matN.shape)
print('matN2:', matN2, 'shape:', matN2.shape)

matN: [[0 1 2]
 [0 0 0]
 [3 4 5]
 [3 4 5]
 [0 1 2]] shape: (5, 3)
matN2: [[0 1 2 0 0]
 [0 3 4 5 3]
 [4 5 0 1 2]] shape: (3, 5)


## Slicing NumPy Array

* we use array slicing to extract a range of elements from the Python array
* we slice and index NumPy arrays in the same ways we slice Python lists
* some examples
  
  
* the first element of the array along the first dimension (axe)

In [67]:
x = matN[0] # the first element of the array along the first dimension (axe)
print(x)

[0 1 2]
[[0 1 2]
 [0 0 0]]


* the first two elements of the array along the axe=0

In [68]:
y = matN[:2] # the first two elements of the array along the axe=0
print(y)

[[0 1 2]
 [0 0 0]]


* extract the first element along the 2nd dimension

In [70]:
z = matN[:, 0]
print(z) # the first two elements of the array along the axe=0

[0 0 3 3 0]


* extract a section of the array

In [74]:
t = matN[1:4, 1:3]
print(t)

[[0 0]
 [4 5]
 [4 5]]


* we can extract elements from the array based on certain conditions

In [82]:
print(matN[matN != 0])
print(matN[(matN <= 3) & (matN > 1)])
print(matN[matN%2 == 0])

[1 2 3 4 5 3 4 5 1 2]
[2 3 3 2]
[0 2 0 0 0 4 4 0 2]


* we use `np.nonzero()` to extract indices from an array based on certain condition

In [84]:
e = np.nonzero(matN > 1)
print(e)

(array([0, 2, 2, 2, 3, 3, 3, 4]), array([2, 0, 1, 2, 0, 1, 2, 2]))


In [85]:
r = list(zip(e[0], e[1]))
print(r)

[(0, 2), (2, 0), (2, 1), (2, 2), (3, 0), (3, 1), (3, 2), (4, 2)]


* we use `np.vstack()` to stack arrays vertically

In [86]:
a = np.array([[1, 1], [3, 3]])
b = np.array([[2, 2], [4, 4]])
v = np.vstack((a, b))
print('a:', a)
print('b:', b)
print('v:', v)

a: [[1 1]
 [3 3]]
b: [[2 2]
 [4 4]]
v: [[1 1]
 [3 3]
 [2 2]
 [4 4]]


* we use `np.hstack()` to stack arrays horizontally

In [88]:
h = np.hstack((a, b))
print('h:', h)

h: [[1 1 2 2]
 [3 3 4 4]]


* we use `np.arange()` to generate a list of integers 

In [95]:
s = np.arange(1, 37)
print(s)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [96]:
w = s.reshape(4, 9)
print(w)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


* we use `np.ones()` to generate an array where all elements are equal to 1

In [118]:
o = np.ones(12)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [119]:
print(o.reshape(2, 3, 2))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


* we use `np.identity()` to generate a square identity array with ones on the main diagonal

In [120]:
id = np.identity(5)
print(id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


* we use `np.random.rand()` to generate a random floats array between 0 an 1

In [131]:
r = np.random.rand(4, 5)
print(r)

[[0.85299007 0.29584367 0.38459538 0.400023   0.41506865]
 [0.3163114  0.11993919 0.97547786 0.19917045 0.97548425]
 [0.86356129 0.19896953 0.24663959 0.43772593 0.10207561]
 [0.66730612 0.61814151 0.92050238 0.29670701 0.37570151]]


* we use `np.hsplit()` to split horizontally an array to small chuncks

In [102]:
x = np.hsplit(w, 3)
print(x)

[array([[ 1,  2,  3],
       [10, 11, 12],
       [19, 20, 21],
       [28, 29, 30]]), array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24],
       [31, 32, 33]]), array([[ 7,  8,  9],
       [16, 17, 18],
       [25, 26, 27],
       [34, 35, 36]])]


* we use `np.vsplit()` to split vertically an array to small chuncks

In [105]:
y = np.vsplit(w, 2)
print(y)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])]


* we use `view` to create a new array that shares the same data (in memory) as the original array (_shallow copy_)

In [113]:
d = w.view() # shallow copy
d[0] = 100
print('d:', d)
print('w:', w)

d: [[100 100 100 100 100 100 100 100 100]
 [ 10  11  12  13  14  15  16  17  18]
 [ 19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36]]
w: [[100 100 100 100 100 100 100 100 100]
 [ 10  11  12  13  14  15  16  17  18]
 [ 19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36]]


In [112]:
f = d.reshape(9, 4) # deep copy
print('d:', d)
print('f:', f)

d: [[100 100 100 100 100 100 100 100 100]
 [ 10  11  12  13  14  15  16  17  18]
 [ 19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36]]
f: [[100 100 100 100]
 [100 100 100 100]
 [100  10  11  12]
 [ 13  14  15  16]
 [ 17  18  19  20]
 [ 21  22  23  24]
 [ 25  26  27  28]
 [ 29  30  31  32]
 [ 33  34  35  36]]


* we use `ndarray.copy()` to make element-wise copy (_deep copy_)

In [115]:
u = w.copy() # deep copy
u[0] = -1
print('w:', w)
print('u:', u)

w: [[100 100 100 100 100 100 100 100 100]
 [ 10  11  12  13  14  15  16  17  18]
 [ 19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36]]
u: [[-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


## Some additional array operations

* we can perform arithmetic (element-wise) operations on arrays (+, -, *, \/)

In [126]:
m = np.arange(1, 19).reshape(3, 6)
g = np.ones(18).reshape(3, 6)
print(m)
print(g)
print(m + g)
print(m - g)
g[1, 3] = 2
print(m * g)
print(m / g)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[ 2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]]
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 20. 11. 12.]
 [13. 14. 15. 16. 17. 18.]]
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9.  5. 11. 12.]
 [13. 14. 15. 16. 17. 18.]]


In [135]:
x = np.random.rand(3, 6) * 10
print(x)

[[0.05388048 3.68526438 8.56195232 7.01967268 9.92931988 2.82696755]
 [4.35378631 4.19012369 5.13189142 2.37789334 3.11135479 2.39096757]
 [4.78577088 4.94608449 5.00428148 5.78190943 4.67798949 9.63085714]]


* we can compute maximum, minimum, sum, mean, product, standard deviation, etc. of an array

In [140]:
print('max:', x.max())
print('min:', x.min())
print('sum:', x.sum())
print('meam:', x.mean())
print('stdv:', x.std())
print('median:', np.median(x))

max: 9.929319880576177
min: 0.053880480065086056
sum: 88.45996731192098
meam: 4.914442628440054
stdv: 2.4988531275161576
median: 4.731880187231791


* the same operations can be performed along a specific axe

In [143]:
print('max:', x.max(axis=0))
print('min:', x.min(axis=1))
print('sum:', x.sum(axis=0))
print('meam:', x.mean(axis=0))
print('stdv:', x.std(axis=1))
print('median:', np.median(x, axis=1))

max: [4.78577088 4.94608449 8.56195232 7.01967268 9.92931988 9.63085714]
min: [0.05388048 2.37789334 4.67798949]
sum: [ 9.19343767 12.82147257 18.69812522 15.17947544 17.71866416 14.84879226]
meam: [3.06447922 4.27382419 6.23270841 5.05982515 5.90622139 4.94959742]
stdv: [3.44626481 1.03737545 1.74764513]
median: [5.35246853 3.65073924 4.97518299]
